### ISSUE TITLE
Build Fails Due to Missing .js.map

### ISSUE THREAD

**Issue by queejie** [monad98/ng2-lazy-trumbowyg#1]
Thank you very much for starting this project.  I'm looking forward to working with it.

I'm getting an error, however, in the javascript console, where it is looking for the trumbowyg.component.js.map file, but it is not in the npm installed directory.  I'm not sure if that is something unique to my setup, or more general.  I'm not sure what is requiring the .map file(s).

Any assistance you can provide would be greatly appreciated.

![nocti_and_introduction_to_javascript_source_maps_-_html5_rocks](https://cloud.githubusercontent.com/assets/1616827/22746832/1d62e1de-edf3-11e6-8641-0d6acfc3423c.png)

I am using ionic 2, and it may have something to do with webpack.

**Comment by monad98** [comment]
I added map files and published v2.0.2
Please try to install again.
If you have any problems, please let me know.

**Comment by queejie** [comment]
Thanks very much!  It works well.  The ionic 2/angular 2 ties together so many new technologies that I'm often not certain if it is something I need to tweak in webpack or npm configuration. 

I was trying to use trumbowyg with just a declare let Trumbowyg, but it didn't work well in a modal page in ionic.  Yours worked right off the bat.

Best regards,
-dqj
