### ISSUE TITLE
How to set data after editor initialization

### ISSUE THREAD

**Issue by uiravi** [monad98/ng2-lazy-trumbowyg#10]
Not able to set data. Please help

**Comment by monad98** [comment]
Please use initialContent input and savedContent output.

**Comment by uiravi** [comment]
initialContent is not working after editor initialization

**Comment by monad98** [comment]
ooops... would you please tell me what exactly you want to do?
The contents are updated automatically through the trumbowyg component and you can get the updated content from (savedContent) output.

**Comment by uiravi** [comment]
After editor loaded in page need to replace editor data by initialContent or another variable.
Please check plunker URL below. need to replace or update text tuner content by onTtcClick method.
https://plnkr.co/edit/J8l5rbW2lWp796QAuUyW?p=preview

**Comment by monad98** [comment]
ok. I got it. I will make some changes and let you know.

**Comment by uiravi** [comment]
Thanks, Please remove or comment console.log. data is showing in console

**Comment by monad98** [comment]
initialContent can be manually updated.
```
constructor() {
    setTimeout(() => {
      this.initialContentOne = "<h1>Contents can be manually updated.</h1>"
      this.update$.next(); // this is needed only when you use ChangeDetectionStrategy.OnPush strategy
    },2000);
  }
```
