### ISSUE TITLE
Copy paste not working

### ISSUE THREAD

**Issue by tejasrivastav** [monad98/ng2-lazy-trumbowyg#11]
When user paste content from cliporboard the text area field is getting updated but the model value is not getting updated.

https://plnkr.co/edit/dirpKmLNalUmz0mpdrk7?p=preview

<code>
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
</code>

**Comment by monad98** [comment]
It works...
Did you check whether you are using live update or observable?

**Comment by tejasrivastav** [comment]
using live update

**Comment by tejasrivastav** [comment]
Attached is the [video recording](https://drive.google.com/file/d/0B0UdJteKyJMpZmliLVdOV3FtTkU/view?usp=sharing) of the same.

**Comment by monad98** [comment]
@tejasrivastav I don't know why it happens, but for me it works fine.

https://www.dropbox.com/s/7beon6a84sip0ul/2017-09-06%2000_23_31.mp4?dl=0

**Comment by tejasrivastav** [comment]
chrome version: Version 57.0.2987.110 (64-bit) 
would this cause any issue

**Comment by monad98** [comment]
my Chrome version is Version 60.0.3112.113
Safari Version 10.1.2 (12603.3.8)
and this works on android chrome (same version)
