### ISSUE TITLE
Cannot add a Placeholder 

### ISSUE THREAD

**Issue by TheBobo** [monad98/ng2-lazy-trumbowyg#13]
I am using Trumbowyg in my Angular2 app
I trying to update my object property [(ngModel)]='scene.description'
but it doesn't work. 

Here is a snippet from my code :

```
<trumbowyg
[(initialContent)]="scene.description" 
[options]="options1"
[(ngModel)]="scene.description"
(savedContent)="scene.description=$event">
```

How I can update my model from Trumbowyg ?

**Comment by monad98** [comment]
Try this.
```
<trumbowyg
[initialContent]="scene.description" 
[options]="options1"
(savedContent)="scene.description=$event">
```
or
```
<trumbowyg
initialContent="This is my initial content" 
[options]="options1"
liveUpdate="true"
(savedContent)="scene.description=$event">
```

For live update, someObj.someProp and scene.description should be different variables.

**Comment by TheBobo** [comment]
it doesn't work

**Comment by monad98** [comment]
show me live app on Plunker or somewhere else.
This is the basic and core feature of this module and should work.
