### ISSUE TITLE
Property 'forRoot' does not exist on type 'typeof TrumbowygModule'.

### ISSUE THREAD

**Issue by Metsuryu** [monad98/ng2-lazy-trumbowyg#17]
I'm working on an Angular 4 CLI project.
In `imports` using just `TrumbowygModule ` works fine, but trying to use it with plugins like this:

`TrumbowygModule.forRoot({plugins: ['colors', 'noembed', 'preformatted', 'pasteimage', 'upload'], version: '2.8.0'})`

Gives the error: Property 'forRoot' does not exist on type 'typeof TrumbowygModule'.

**Comment by monad98** [comment]
What version of this module are you using?

**Comment by monad98** [comment]
check this live app. It's using ng2-lazy-trumbowyg version 2.4.2
https://plnkr.co/edit/dirpKmLNalUmz0mpdrk7?p=preview

**Comment by Metsuryu** [comment]
"ng2-lazy-trumbowyg": "^2.3.3"

**Comment by monad98** [comment]
@Metsuryu You can use plug-ins and version config after V.2.4.1

**Comment by Metsuryu** [comment]
Thank you, it works now, you can close the issue.
