### ISSUE TITLE
How to change styles

### ISSUE THREAD

**Issue by Metsuryu** [monad98/ng2-lazy-trumbowyg#18]
I'm sorry to bother you again, but I can't find a way to change the style of the editor.

The official documentation says to make a copy of the /src/ui/ folder and edit the css in that, but in ng2-lazy-trumbowyg there are no css/style files that I can see.
https://alex-d.github.io/Trumbowyg/documentation/#custom-skin

Where are you taking the styles from, and is there a way to customize them?

**Comment by monad98** [comment]
Sorry, but custom skin is not supported (yet).

**Comment by Metsuryu** [comment]
I see. Do you plan to implement it in the near future? I might give you a hand with that if you want.

**Comment by monad98** [comment]
You can pull merge request. :) Thanks.

**Comment by Metsuryu** [comment]
So far I saw you're appending to the head the default editor's css, but it's modified so that after each tag there is a [_ngcontent-c3].

If I try to style the editor on my own for some reason it doesn't work, maybe it gets overridden by the file appended to the head.

To avoid adding this css to the head in a quick and dirty way for now, so that I can edit them on my local css, could I just check for a boolean to make the appening optional (opt-out) somehow?

**Comment by monad98** [comment]
you mean..giving users the option to decide to include default css or not? It looks easy. Do you have another idea?

**Comment by Metsuryu** [comment]
Yeah, just a quick and very dirty temporary option. 
For now I just solved my problem so I don't need it right now anymore, but in the future it could be a useful option.
