### ISSUE TITLE
Copy Paste doesn't work correctly (IE11)

### ISSUE THREAD

**Issue by svitlanaAntoniuk** [monad98/ng2-lazy-trumbowyg#23]
Here is a plunker: https://plnkr.co/edit/dRQ8oPbY8ZUSwRIyEAwj?p=preview

When I'm trying to paste value from cliporboard - value is not updated correctly.

**Comment by monad98** [comment]
What does 'not correctly' mean? Doesn't it update at all? or is different value pasted?

**Comment by svitlanaAntoniuk** [comment]
If text editor is empty and I'm trying to paste some text (e.g. "test1") - text is successfully  pasted in editor but  "contentOne" field value is empty string.
When trying to paste text one more time - text in editor becomes "test1test1" but "contentOne" contains only "test1" text.

**Comment by monad98** [comment]
Does it happen only with IE11?
It seems to work fine with the latest Chrome and Safari

**Comment by svitlanaAntoniuk** [comment]
As I mentioned in description reproduced in IE11. Issue is not reproducible in Chrome

**Comment by monad98** [comment]
Ok. Actually, I don't have Windows pc, so give me a few days to check.

**Comment by svitlanaAntoniuk** [comment]
Please let me know if you need more information. Will be waiting for solution. Thanks.

**Comment by svitlanaAntoniuk** [comment]
Are there any updates regarding this issue?

**Comment by PitPanda1** [comment]
I'm having the same problem (seems to be a crossbrowser problem). Just tested in Chrome with your  demo project the second wysiwyg.

`(ctrl + v)` -> no event
`(ctrl + a) + del` -> no event
`(ctrl + a) + backspace` -> no event
`(ctrl + a) + space` -> no event
`(ctrl + a) + <anykey>` -> no event

**Comment by monad98** [comment]
Ok. Let me fix this issue tonight.

**Comment by monad98** [comment]
@PitPanda1 can you check if it works now?
@svitlanaAntoniuk  I didn't get windows pc yet, but can you check whether the problem still exists?

**Comment by PitPanda1** [comment]
@monad98 
Hey, yes it seems to work now. 👍
