### ISSUE TITLE
In "npm install", trumbowyg not downloading all its dependencies

### ISSUE THREAD

**Issue by srigar** [monad98/ng2-lazy-trumbowyg#24]
I just did all the steps as given and it is working fine in dev env. After development i put my production build(ng serve --prod) into my server. From server it is trying to download two of its dependencies 
1.https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.8.0/ui/trumbowyg.min.css
2.https://cdnjs.cloudflare.com/ajax/libs/Trumbowyg/2.8.0/trumbowyg.min.js
But the problem is i dont have internet connection in my server(Completely Intranet). Why it is not downloaded all its dependencies at the build time and what is the work around for that?
![capture](https://user-images.githubusercontent.com/20384652/35505690-df97cdb0-050c-11e8-983b-762fd27bdde3.PNG)

**Comment by srigar** [comment]
Can you please help me out with this?

**Comment by monad98** [comment]
I think you can save those two files locally and change the source code to point local address like localhost:4200/trumbowyg.min.css

**Comment by srigar** [comment]
Ok let me try that.
