### ISSUE TITLE
ERROR in TrumbowygModule is not an NgModule

### ISSUE THREAD

**Issue by fergalmoran** [monad98/ng2-lazy-trumbowyg#3]
I'm getting this since the 2.0.3 release?
Create a new angular-cli (1.0.0) project
npm install --save ng2-lazy-trumbowyg

add the import to app.module.ts

`ERROR in TrumbowygModule is not an NgModule
webpack: Failed to compile.`

**Comment by monad98** [comment]
I only checked system js. I'll take a look.
Thanks.

**Comment by monad98** [comment]
Looks like working with angular cli 1.0.0
check this repo. It's angular-cli quickstart project + this module.
https://github.com/monad98/ng2-lazy-trumbowyg-example-angularCLI

**Comment by monad98** [comment]
Ok. now I see what the problem is.
https://github.com/angular/angular-cli/issues/3426
I will try to fix ASAP

**Comment by monad98** [comment]
@fergalmoran Fixed. Thanks.

**Comment by fergalmoran** [comment]
Just checked it there in my project and it works perfectly!
Thanks so much for your quick fix and this great library!
