### ISSUE TITLE
AOT: Property 'savedContent' is private and only accessible within class 'Trumbowyg'

### ISSUE THREAD

**Issue by vaaguirre** [monad98/ng2-lazy-trumbowyg#4]
When running my app with the --aot flag, I get this error:

`Property 'savedContent' is private and only accessible within class 'Trumbowyg'.`

Tu run with AOT compiler, ngc needs properties to be public. I've been trying to go around this but have failed. Have you used this component with AOT? Can you give an example? Otherwise, I could do a pull request with the fix, so you could update the npm package.

**Comment by monad98** [comment]
Ok, please create a pull request. I am outside today, so I will check tomorrow.

**Comment by vaaguirre** [comment]
I created the pull request #5

**Comment by monad98** [comment]
ok. fixed with v2.2.2
Thank you.
