### ISSUE TITLE
Facing issue while using in Ionic 2

### ISSUE THREAD

**Issue by satishtech** [monad98/ng2-lazy-trumbowyg#9]
Hi, 
This seems to be clean & neat rich text editor component.
I would like to use in ionic 2. But, I am facing issues. 

> 'trumbowyg' is not a known element

Kindly Let me know, how can we use this.

Thanks,

**Comment by monad98** [comment]
I just tested and it works with Ionic 3
Maybe it's because you didn't import TrumbowygModule.

**Comment by satishtech** [comment]
First, I would like to thank you for immediate response.

All of a sudden!!!, it worked neatly today. 
1. Just created new sample tab ionic app.
2. npm install ng2-lazy-trumbowyg --save
3. import in app.module.ts 
4. Insterted the `<trumbowyg liveUpdate="true" 
               [initialContent]="initialContentTwo"
               [options]="options2"
               (savedContent)="contentTwo=$event">
    </trumbowyg>` in home template.
5. declaring the values for options & initialContent in home ts file.

Worked perfectly today.
I m confused, why i got the errors yesterday, where i followed same steps couple of times.

**Comment by monad98** [comment]
Thank you and good to know that it works now.

**Comment by satishtech** [comment]
Hi,

Need below clarification.

> <trumbowyg liveUpdate="true" [initialContent]="this.varname" [options]="optionsval" > </trumbowyg>

How to update the value of "varname". & how to trigger the method during value change.

**Comment by satishtech** [comment]
> savedContent
savedContent is used to update the value.

I would like to trigger method during onchange [ie., while editing] in text editor. What is the possibility.

**Comment by monad98** [comment]
Why are you trying to change initialContent which is varname in you case? It's just an initial string. You can do this
```
<trumbowyg liveUpdate="true" 
               [initialContent]="varname"
               [options]="optionsval"
               (savedContent)="convertThisToThat($event)"> 
<div [innerHTML]="content"></div>

convertThisToThat(ev) {
    this.content = ev.replace(/This/gi, 'That');
}
```
or use pipe
```
<div [innerHTML]="content | highlight: 'title'"></div> //'title' text will be highlighted
```

**Comment by satishtech** [comment]
Thanks for the inputs. Its very useful.
